version: '2'
services:
  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - target: 6379
        published: 6371
        protocol: tcp
        mode: host
    volumes:
      - redis-cluster_data-1:/tmp/redis/data/
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - target: 6379
        published: 6372
        protocol: tcp
        mode: host
    volumes:
      - redis-cluster_data-2:/tmp/redis/data/
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - target: 6379
        published: 6373
        protocol: tcp
        mode: host
    volumes:
      - redis-cluster_data-2:/tmp/redis/data/
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - target: 6379
        published: 6374
        protocol: tcp
        mode: host
    volumes:
      - redis-cluster_data-4:/tmp/redis/data/
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - target: 6379
        published: 6375
        protocol: tcp
        mode: host
    volumes:
      - redis-cluster_data-5:/tmp/redis/data/
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-6:
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - target: 6379
        published: 6376
        protocol: tcp
        mode: host
    volumes:
      - redis-cluster_data-6:/bitnami/redis/data/
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
  redis-cluster_data-6:
    driver: local